apiVersion: v1
kind: Service
metadata:
  name: webook-record
spec:
  type: LoadBalancer
  selector:
    app: webook-record
  ports:
    - protocol: TCP
      port: 8080 #云服务器上用的是8080
      targetPort: 8080

  